[platformio]
default_envs = esp32-focus

[env:esp32-focus]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = /dev/ttyUSB1
monitor_port = /dev/ttyUSB1
lib_deps =
  bodmer/TFT_eSPI@2.5.43
build_flags =
  -D USER_SETUP_LOADED=1
  -D ILI9341_DRIVER=1
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=320
  -D TFT_MISO=12
  -D TFT_MOSI=13
  -D TFT_SCLK=14
  -D TFT_CS=15
  -D TFT_DC=2
  -D TFT_RST=-1
  -D TFT_BL=21
  -D TFT_BACKLIGHT_ON=HIGH
  -D USE_HSPI_PORT=1
  -D DISABLE_ALL_LIBRARY_WARNINGS=1
  -D SPI_FREQUENCY=26000000
  -D SPI_READ_FREQUENCY=8000000
  -D LOAD_GLCD=1
  -D LOAD_FONT2=1
  -D LOAD_FONT7=1

[env:esp32-focus-self-test]
extends = env:esp32-focus
build_flags =
  ${env:esp32-focus.build_flags}
  -D ESP32_FOCUS_SELF_TEST=1
